---
- name: Clean pki path
  file:
    state: absent
    path: "{{ pki_path }}/"

- name: easyrsa init-pki
  command: "/etc/openvpn/easy-rsa/easyrsa init-pki"

- name: easyrsa build-ca
  expect:
    command: /etc/openvpn/easy-rsa/easyrsa build-ca
    responses:
      (?i)Passphrase: "{{vars.Passphrase}}"
      (?i)Re-Enter New CA Key Passphrase: "{{vars.Passphrase}}"
      (?i)]: "{{vars.Common_Name}}"

- name: easyrsa gen-req
  expect:
    command: /etc/openvpn/easy-rsa/easyrsa gen-req server nopass
    responses:
      (?i)[server]: "{{vars.servername}}"

- name: easyrsa sign-req
  expect:
    command: /etc/openvpn/easy-rsa/easyrsa sign-req server server
    responses:
      (?i)details: "yes"
      (?i)ca.key: "{{vars.pass}}"

- name: easyrsa gen-dh
  command: /etc/openvpn/easy-rsa/easyrsa gen-dh

- name: Removing dh.pem
  file:
    path: /etc/openvpn/dh.pem
    state: absent

- name: Removing server.key
  file:
    path: /etc/openvpn/server.key
    state: absent

- name: Removing ca.crt
  file:
    path: /etc/openvpn/ca.crt
    state: absent

- name: Removing server.crt
  file:
    path: /etc/openvpn/server.crt
    state: absent

- name: copy dh.pem
  copy:
    src: pki/dh.pem
    dest: /etc/openvpn

- name: copy server.key
  copy:
    src: pki/private/server.key
    dest: /etc/openvpn

- name: copy ca.crt
  copy:
    src: pki/ca.crt
    dest: /etc/openvpn

- name: copy server.crt
  copy:
    src: pki/issued/server.crt
    dest: /etc/openvpn

- name: Restart Server openvpn
  service:
    name: openvpn
    state: restarted
          

#cp ./pki/dh.pem /etc/openvpn/dh1024.pem
#cp ./pki/private/client.key /etc/openvpn/
#cp ./pki/private/server.key /etc/openvpn/
#cp ./pki/ca.crt /etc/openvpn/
#cp ./pki/issued/client.crt /etc/openvpn/
#cp ./pki/issued/server.crt /etc/openvpn/
